services:
  - type: web
    name: file-converter-api
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y libreoffice
      cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11